Feat/performance
OpenWebconcept/plugin-openagenda-base pull request #24
Opened 2024-05-14 12:08 UTC by ictbeheer

2024-05-15 08:14 UTC, richardkorthuis requested changes

2024-05-15 08:14 UTC, richardkorthuis commented on src/admin/class-event-dates.php
> +		add_action( 'openagenda_update_next_event_date', array ( $this, 'update_next_event_date' ));
Algemeen: Wij hanteren de WordPress Coding Standards, ik zie in deze class wat kleine dingen die niet helemaal kloppen. Als je in de plugin directory `composer install` runt, kun je daarna de code laten checken met het commando:
`./vendor/bin/phpcs --standard=phpcs.xml.dist .`
Volgens mij kunnen de meeste fouten automatisch voor je worden gefixt met het commando:
`./vendor/bin/phpcbf --standard=phpcs.xml.dist .`

2024-05-16 07:25 UTC, ictbeheer commented on src/admin/class-cmb2.php
> +					'data-conditional-required' => 'required',
Dat had ik ook eerst, maar dat werkt niet voor velden die conditioneel verborgen zijn. (Deze blokkeren dan altijd het opslaan van de post)

2024-05-17 10:40 UTC, richardkorthuis commented on src/admin/class-cmb2.php
> +					'data-conditional-required' => 'required',
Hmm valide punt, dan moeten we de REST API daar misschien maar op aanpassen dat hij ook dit attribute controleert.

2024-05-17 10:40 UTC, richardkorthuis approved these changes

2024-05-17 10:41 UTC, merged